### ISSUE TITLE
Notifications? What notifications?

### ISSUE THREAD

**Issue by xdisplayx** [mikaelbr/gulp-notify#120] opened 2017-11-05 20:05 UTC
Awesome the data of this add-on!

 3,353 downloads in the last day
82,181 downloads in the last week
365,120 downloads in the last month 

But the support is bad, the complement does not work for weeks and they do not give a solution!

**Comment by mikaelbr** [comment] 2017-11-05 20:35
Hi. Remember that Open Source doesn't come with an support deal. Maintainers aren't obligated to work for you for free. I'm sorry, that's just now how it works. If you have a particular issue and it isn't fixed you have a couple of alternatives:

1. Fix it and provide a patch. Most likely it will get merged, and it's very appriciated.
2. If you aren't able to do 1. yourself, get someone to fix it and provide a patch. Then see point 1.
3. Don't use the plugin.

Remember, I don't get anything out of you using it. It may sound harsh, I'm not trying to be. I'm just trying to tell you how it is from a maintainer point of view. People use the plugin in many different environments, in very different ways. It's impossible for one person to reproduce all cases. Open Source rely on merging changes from others, not just leeching on the work of others.

**Closed by mikaelbr** 2017-11-05 20:35 UTC

**Comment by xdisplayx** [comment] 2017-11-06 17:33
Do not worry and stop using it (5 days worked).
And if I knew how to solve that error, it would be done.

Here is the usual story of open source, as soon as someone does not lick their asses and tells them the 4 truths, they always come out with the same story.


No te preocupes ya deje de usarlo (5 dias funciono).
Y si yo supiera solucionar ese error, ya estaria hecho. 

He aqui el cuento de siempre del codigo abierto, en cuanto alguien no les lame el culo y les dice las 4 verdades, siempre salen con la misma historia.

**Comment by mikaelbr** [comment] 2017-11-07 17:00
@xdisplayx I think you have to dial it back some. You are coming across as very aggressive, for no reason at all. Both here and in the node-notifier repo. Quote:

> "Can anyone with this version of Windows try to fix the issue with snoretoast? I don't have access to this Windows at the current time."
> 
> What a pilgrim excuse!
> https://www.virtualbox.org/
> https://www.microsoft.com/es-mx/software-download/windows10

(which I have removed as it brings nothing to the discussion, except you seeming very hostile).

This shouldn't be your mission. Move on, fix it or don't use it. Drop the entitlement.

**Comment by xdisplayx** [comment] 2017-11-07 17:08
You started with aggression! My first comment was a constructive criticism. And now after seeing this repository for a little while, you only dedicate yourself to erase the comments that do not fit you.

Tu comenzaste con la agresividad! mi primer comentario fue una critica constructiva. Y ahora despues de ver por un poco tiempo este repostorio, tu solo te dedicas a borrar los comentarios que no te convienen.

**Comment by mikaelbr** [comment] 2017-11-07 17:17
Consider this: During the 5+ years these repos have existed. The only comment I've ever deleted is yours. And it's due to your comment being very condescending. And I referred to it here for openness. Saying I erase the comments that don't fit me is just plain wrong. From my point of view, you need a better definition of constructiveness, because all this is destructive.
