### ISSUE TITLE
gulp-notify spawn EACCES

### ISSUE THREAD

**Issue by gustavobissolli** [mikaelbr/gulp-notify#112] opened 2016-07-12 05:16 UTC
Hi guys!

I am using Laravel Valet environment with Elixir and I am facing that following issue with gulp-notify:

https://transfer.sh/13bfYe/screen-shot-2016-07-12-at-01.56.34.png

Somebody knows how to fix it?

**Comment by rovo79** [comment] 2016-07-18 18:28
May be unrelated, but do you have Node Notifier installed? 
https://github.com/mikaelbr/node-notifier

**Comment by davebeach** [comment] 2016-09-09 03:22
I am getting the same thing on mac os x.

[20:22:16] Starting 'sass'...
[20:22:17] gulp-notify: [SASS Compiled] All SASS files have been recompiled to CSS.
[20:22:17] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
Message:
    spawn EACCES
Details:
    code: EACCES
    errno: EACCES
    syscall: spawn
[20:22:17] Finished 'sass' after 710 ms

**Comment by mikaelbr** [comment] 2016-09-09 10:56
`EACCES`  seems to be caused by the process not having enough access to the underlying vendor executable (terminal-notifier.app inside the node-notifier module). This maybe caused by installing the node packages as administrator (sudo) or some other users that the current user doesn't have access to. You can try something like changing the owner to the current user on the node_modules directory (node-notifier package). Something like `sudo chmod -R a+rwx ...`. Does that make sense?

**Comment by joshlewis** [comment] 2016-11-08 00:18
@mikaelbr Thank you!

**Comment by gustavobissolli** [comment] 2016-11-23 19:24
Sorry for the late feedback but I solved the problem deleting my node_modules folder and running npm install again!

**Comment by mikaelbr** [comment] 2016-11-23 22:07
Great. Closing this.

**Closed by mikaelbr** 2016-11-23 22:07 UTC

**Comment by regepan** [comment] 2017-09-11 10:49
I got same error on
```
$ node -v
v6.9.4
```
But the error is hidden after I upgraded to
```
$ node -v
v8.4.0
```
No need to change permission.
